package exceptiontask;

public class TestName 
{
	public static void main(String[] args) throws RuntimeException
	{
		NameException n=new NameException();
		n.Name("Anu", "R");
	}
}
